esphome:
  name: esphome-web-26232c
  friendly_name: ESPHome Web 26232c
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:
api:
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# NeoPixel / WS2812 configuration using ESP32 RMT LED Strip
light:
  - platform: esp32_rmt_led_strip
    id: neopixel_strip
    pin: 23
    num_leds: 8
    chipset: WS2812
    name: "NeoPixel Strip"
    rgb_order: GRB
    default_transition_length: 0s
    effects:
      - flicker:
          name: Flicker
