esphome:
  name: esphome-web-26232c
  friendly_name: ESPHome Web 26232c
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

light:
  - platform: esp32_rmt_led_strip
    id: neopixel_strip
    pin: 23
    num_leds: 8
    chipset: WS2812
    rgb_order: GRB
    name: "NeoPixel Strip"
    effects:
      - flicker:
          name: Flicker

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode: 
        input: true
        pulldown: true
    name: "Lantern button"
    id: lantern_button


    on_multi_click:
      # Single short click (press then release quickly)
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: neopixel_strip

      # Long press
      - timing:
          - ON for at least 1s
        then:
          - light.turn_on:
              id: neopixel_strip
              effect: Flicker

