esphome:
  name: esphome-web-26232c
  friendly_name: ESPHome Web 26232c
  min_version: 2025.9.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


light:
  - platform: esp32_rmt_led_strip
    id: neopixel_strip
    pin: 23
    num_leds: 8
    chipset: WS2812
    rgb_order: GRB
    name: "NeoPixel Strip"
    effects:
      - flicker:
          name: Flicker

globals:
  - id: current_color
    type: int
    restore_value: true
    initial_value: '0'

binary_sensor:
  - platform: gpio
    pin:
      number: 14
      mode:
        input: true
        pulldown: true
    name: "Lantern button"
    id: lantern_button
    filters:
      - delayed_on: 30ms    # software debounce
      - delayed_off: 30ms
    on_multi_click:
      # Single short click → toggle on/off
      - timing:
          - ON for at most 0.5s
          - OFF for at least 0.3s
        then:
          - if:
              condition:
                light.is_on: neopixel_strip
              then:
                - light.turn_off: neopixel_strip
              else:
                - if:
                    condition:
                      lambda: 'return id(current_color) == 0;'
                    then:
                      - light.turn_on:
                          id: neopixel_strip
                          effect: Flicker
                          red: 1.0
                          green: 0.54
                          blue: 0.05    # Color 1
                    else:
                      - light.turn_on:
                          id: neopixel_strip
                          effect: Flicker
                          red: 0.251
                          green: 0.502
                          blue: 1.0    # Color 2

      # Double click → switch color
      - timing:
          - ON for at most 0.5s
          - OFF for at most 0.3s
          - ON for at most 0.5s
        then:
          - lambda: |-
              if (id(current_color) == 0) {
                id(current_color) = 1;
              } else {
                id(current_color) = 0;
              }
          - if:
              condition:
                light.is_on: neopixel_strip
              then:
                - if:
                    condition:
                      lambda: 'return id(current_color) == 0;'
                    then:
                      - light.turn_on:
                          id: neopixel_strip
                          effect: Flicker
                          red: 1.0
                          green: 0.54
                          blue: 0.05
                    else:
                      - light.turn_on:
                          id: neopixel_strip
                          effect: Flicker
                          red: 0.251
                          green: 0.502
                          blue: 1.0
